(function (){

    var doc = app.activeDocument;
    //files
    var image_filepath = doc.path+"/"+doc.name;
    var appdir = "~/_blenderextpaint_autorefresh";
    var syncf = new File(appdir+"/sync.txt");

    //////////////////////////////////////////////////////////////////////////////////////
    //skip ignored layers and layer sets by making them invisible before saving the image
    //////////////////////////////////////////////////////////////////////////////////////
    var made_invisible = new Array();
    //ignored base level layers
    for(var i=0; i < doc.layers.length; i++){
	if(doc.layers[i].name.substring(0,6)=="ignore"){
	    if(doc.layers[i].visible==true){made_invisible.push(doc.layers[i]);}
	    doc.layers[i].visible = false;
	}
    }
    //depth-first search (to make ignored layers and layer sets invisible), starting on base level layer sets
    var stack = new Array();
    for(var i=0; i < doc.layerSets.length; i++){stack[i]=doc.layerSets[i];}
    while(stack.length > 0){
	var layer_set = stack.pop();
	//visit. ignored layer sets
	if(layer_set.name.substring(0,6)=="ignore"){
	    if(layer_set.visible){made_invisible.push(layer_set);}
	    layer_set.visible = false;
	    continue;
	}
	else{
	    //ignored layers in layer set
	    for(var i=0; i < layer_set.layers.length; i++){
		if(layer_set.layers[i].name.substring(0,6)=="ignore"){
		    if(layer_set.layers[i].visible==true){made_invisible.push(layer_set.layers[i]);}
		    layer_set.layers[i].visible = false;
		}
	    }
	}
	//add sub layer sets to stack
	for(var i=0; i < layer_set.layerSets.length; i++){stack.push(layer_set.layerSets[i]);}
    }

    /////////////////
    //save the image
    /////////////////
    try{
	////////////code generated by photoshop script listener plugin to save png with default compression////////////////
	var idsave = charIDToTypeID("save");
	var desc21 = new ActionDescriptor();
	var idIn = charIDToTypeID("In  ");
	desc21.putPath(idIn, new File(image_filepath));
	var idsaveStage = stringIDToTypeID("saveStage");
	var idsaveStageType = stringIDToTypeID("saveStageType");
	var idsaveBegin = stringIDToTypeID("saveBegin");
	desc21.putEnumerated(idsaveStage, idsaveStageType, idsaveBegin);
	var idDocI = charIDToTypeID("DocI");
	desc21.putInteger(idDocI, 1128);
	executeAction(idsave, desc21, DialogModes.NO);
    }catch(e){}

    //for the ignored layers that were made invisible earlier, make them visible again
    for(var i=0; i < made_invisible.length; i++){made_invisible[i].visible=true;}

    ////////////////////////////////////
    //done saving image, let blender go
    ////////////////////////////////////
    try{
	syncf.open('w');
	syncf.writeln("blender");
	syncf.close();
    }catch(e){}
})();




