(function (){
    var doc = app.activeDocument;
    //files
    var appdir = "~/_blenderextpaint_autorefresh";
    var image_filepath = doc.path+"/"+doc.name;
    var syncf = new File(appdir+"/sync.txt");

    /////////////////////
    //image place-reload
    /////////////////////
    try{
	var layer_name = doc.activeLayer.name;

	////////////code generated by photoshop script listener plugin to select all in the current layer////////////////
	var idsetd = charIDToTypeID( "setd" );
	var desc84 = new ActionDescriptor();
	var idnull = charIDToTypeID( "null" );
	var ref56 = new ActionReference();
	var idChnl = charIDToTypeID( "Chnl" );
	var idfsel = charIDToTypeID( "fsel" );
	ref56.putProperty( idChnl, idfsel );
	desc84.putReference( idnull, ref56 );
	var idT = charIDToTypeID( "T   " );
	var idOrdn = charIDToTypeID( "Ordn" );
	var idAl = charIDToTypeID( "Al  " );
	desc84.putEnumerated( idT, idOrdn, idAl );
	executeAction( idsetd, desc84, DialogModes.NO );
	////////////code generated by photoshop script listener plugin to delete the selection, thus clearing the layer////////////////
	var idDlt = charIDToTypeID( "Dlt " );
	executeAction( idDlt, undefined, DialogModes.NO );
	////////////code generated by photoshop script listener plugin to place image into the cleared layer////////////////
	var idPlc = charIDToTypeID( "Plc " );
	var desc93 = new ActionDescriptor();
	var idnull = charIDToTypeID( "null" );
	desc93.putPath( idnull, new File(image_filepath) );
	var idFTcs = charIDToTypeID( "FTcs" );
	var idQCSt = charIDToTypeID( "QCSt" );
	var idQcsa = charIDToTypeID( "Qcsa" );
	desc93.putEnumerated( idFTcs, idQCSt, idQcsa );
	var idOfst = charIDToTypeID( "Ofst" );
	var desc94 = new ActionDescriptor();
	var idHrzn = charIDToTypeID( "Hrzn" );
	var idPxl = charIDToTypeID( "#Pxl" );
	desc94.putUnitDouble( idHrzn, idPxl, 0.000000 );
	var idVrtc = charIDToTypeID( "Vrtc" );
	var idPxl = charIDToTypeID( "#Pxl" );
	desc94.putUnitDouble( idVrtc, idPxl, 0.000000 );
	var idOfst = charIDToTypeID( "Ofst" );
	desc93.putObject( idOfst, idOfst, desc94 );
	executeAction( idPlc, desc93, DialogModes.NO );
	////////////code generated by photoshop script listener plugin to rasterize the placed layer (need to do this after placing)////////////////
	var idrasterizeLayer = stringIDToTypeID( "rasterizeLayer" );
	var desc28 = new ActionDescriptor();
	var idnull = charIDToTypeID( "null" );
	var ref15 = new ActionReference();
	var idLyr = charIDToTypeID( "Lyr " );
	var idOrdn = charIDToTypeID( "Ordn" );
	var idTrgt = charIDToTypeID( "Trgt" );
	ref15.putEnumerated( idLyr, idOrdn, idTrgt );
	desc28.putReference( idnull, ref15 );
	executeAction( idrasterizeLayer, desc28, DialogModes.NO );

	//reloaded layer and name
	doc.activeLayer.name = layer_name;
	var active_layer = doc.activeLayer;
    }catch(e){}

    //let blender go
    try{
	syncf.open('w');
	syncf.writeln("blender");
	syncf.close();
    }catch(e){}
})();




