(function (){

    var doc = app.activeDocument;
    //files
    var image_filepath = doc.path+"/"+doc.name;
    var appdir = "~/_blenderextpaint_autorefresh";
    var syncf = new File(appdir+"/sync.txt");

    //////////////////////////////////////////////////////////////////////////////////////
    //skip ignored layers and layer sets by making them invisible before saving the image
    //////////////////////////////////////////////////////////////////////////////////////
    var made_invisible = new Array();
    //ignored base level layers
    for(var i=0; i < doc.layers.length; i++){
	if(doc.layers[i].name.substring(0,6)=="ignore"){
	    if(doc.layers[i].visible==true){made_invisible.push(doc.layers[i]);}
	    doc.layers[i].visible = false;
	}
    }
    //depth-first search (to make ignored layers and layer sets invisible), starting on base level layer sets
    var stack = new Array();
    for(var i=0; i < doc.layerSets.length; i++){stack[i]=doc.layerSets[i];}
    while(stack.length > 0){
	var layer_set = stack.pop();
	//visit ignored layer sets
	if(layer_set.name.substring(0,6)=="ignore"){
	    if(layer_set.visible){made_invisible.push(layer_set);}
	    layer_set.visible = false;
	    continue;
	}
	else{
	    //ignored layers in layer set
	    for(var i=0; i < layer_set.layers.length; i++){
		if(layer_set.layers[i].name.substring(0,6)=="ignore"){
		    if(layer_set.layers[i].visible==true){made_invisible.push(layer_set.layers[i]);}
		    layer_set.layers[i].visible = false;
		}
	    }
	}
	//add sub layer sets to stack
	for(var i=0; i < layer_set.layerSets.length; i++){stack.push(layer_set.layerSets[i]);}
    }
    
    /////////////////
    //save the image
    /////////////////
    try{
	////////////code generated by photoshop script listener plugin to save png with compression set to 1////////////////
	var idsave = charIDToTypeID( "save" );
	var desc629 = new ActionDescriptor();
	var idAs = charIDToTypeID( "As  " );
	var desc630 = new ActionDescriptor();
	var idPGIT = charIDToTypeID( "PGIT" );
	var idPGIT = charIDToTypeID( "PGIT" );
	var idPGIN = charIDToTypeID( "PGIN" );
	desc630.putEnumerated( idPGIT, idPGIT, idPGIN );
	var idPNGf = charIDToTypeID( "PNGf" );
	var idPNGf = charIDToTypeID( "PNGf" );
	var idPGAd = charIDToTypeID( "PGAd" );
	desc630.putEnumerated( idPNGf, idPNGf, idPGAd );
	var idCmpr = charIDToTypeID( "Cmpr" );
	desc630.putInteger( idCmpr, 1 );
	var idPNGF = charIDToTypeID( "PNGF" );
	desc629.putObject( idAs, idPNGF, desc630 );
	var idIn = charIDToTypeID( "In  " );
	desc629.putPath( idIn, new File( image_filepath ) );
	var idDocI = charIDToTypeID( "DocI" );
	desc629.putInteger( idDocI, 2610 );
	var idsaveStage = stringIDToTypeID( "saveStage" );
	var idsaveStageType = stringIDToTypeID( "saveStageType" );
	var idsaveSucceeded = stringIDToTypeID( "saveSucceeded" );
	desc629.putEnumerated( idsaveStage, idsaveStageType, idsaveSucceeded );
	executeAction( idsave, desc629, DialogModes.NO );
    }catch(e){}

    //for the ignored layers that were made invisible earlier, make them visible again
    for(var i=0; i < made_invisible.length; i++){made_invisible[i].visible=true;}

    ////////////////////////////////////////
    //done saving the image, let blender go
    ////////////////////////////////////////
    try{
	syncf.open('w');
	syncf.writeln("blender");
	syncf.close();
    }catch(e){}
})();




